#include "esp_http_server.h"
#include "esp_log.h"
#include "wifi_scan.h"
#include "index_content.h"   // This includes the header generated by the Python script
#define TAG "WebServer"

// Handler for serving the index.html content directly from the array
static esp_err_t index_handler(httpd_req_t *req) {
    // Send the index.html content from the array as a response
    httpd_resp_send(req, (const char *)INDEX_CONTENT, INDEX_CONTENT_SIZE);
    return ESP_OK;
}
// Handler for scanning Wi-Fi networks
static esp_err_t wifi_scan_handler(httpd_req_t *req) {
    ESP_LOGI(TAG, "Received Wi-Fi scan request");

    wifi_scan();  // Perform Wi-Fi scan
    const char *response = wifi_scan_get_results(); // Get scan results in JSON format

    if (response == NULL || strlen(response) == 0) {
        httpd_resp_send_500(req);
        return ESP_FAIL;
    }

    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, response, strlen(response));

    return ESP_OK;
}

// Define URI handlers
httpd_uri_t uri_get = {
    .uri = "/",
    .method = HTTP_GET,
    .handler = index_handler,
    .user_ctx = NULL
};

httpd_uri_t uri_scan = {
    .uri = "/scan",
    .method = HTTP_GET,
    .handler = wifi_scan_handler,
    .user_ctx = NULL
};

// Start the web server and register URI handlers
httpd_handle_t start_webserver(void) {
    httpd_config_t config = HTTPD_DEFAULT_CONFIG();
    httpd_handle_t server = NULL;

    if (httpd_start(&server, &config) == ESP_OK) {
        httpd_register_uri_handler(server, &uri_get);
        httpd_register_uri_handler(server, &uri_scan);
        ESP_LOGI(TAG, "Web Server started");
    } else {
        ESP_LOGE(TAG, "Failed to start web server");
    }

    return server;
}
